name: License Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install LicenseFinder
        run: gem install license_finder
      - name: Run LicenseFinder
        run: license_finder
